# Pandas Training Book

### Why I made this notebook?

This Notebook is here to train the Pandas Library. 
It contains quizzles for all fundamental Pandas attributes, methods and more. 
The goal is to **master the mechanics through repetition**. 
The work here is based on the book "Python Data Science Handbook" written by Jack VanderPlas, which I really enjoyed reading.

### Requirements

You should know the theory behind numpy and have an understanding why the following tasks work.
This book is just about knowing how to use the code.

### Let's get started

#### Task 1 Installation

1.1 Import Pandas

In [1]:
import pandas as pd

In [2]:
#enter solution


1.2 Show Pandas version

In [3]:
pd.__version__

'1.0.3'

In [4]:
#enter solution


1.3 Import the other library, that panda works with

In [5]:
import numpy as np

In [6]:
#enter solution


#### Task 2 Introducing Pandas Objects

2.1 Create a pandas series with the values 1, 2 , 3 , 4 and save it in the variable **data**

In [7]:
data = pd.Series([1, 2, 3, 4])
data

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
#enter solution


2.2 Get the values from the **data** object

In [9]:
data.values

array([1, 2, 3, 4], dtype=int64)

In [10]:
#enter solution


2.3 Show the index-range from the **data** object

In [11]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
#enter solution


2.4 Get the second item from the **data** object

In [13]:
data[1]

2

In [14]:
#enter solution


2.5 Get the values from index 1 to 2

In [15]:
data[1:3]

1    2
2    3
dtype: int64

In [16]:
#enter solution


2.6 create a pandas series with the values 1, 2, 3, 4 and indices a, b, c, d and save it in the varibale **data**

In [17]:
data = pd.Series([1,2,3,4], index=["a", "b", "c", "d"])
data

a    1
b    2
c    3
d    4
dtype: int64

In [18]:
#enter solution


2.7 Get the item for the index "b"

In [19]:
data["b"]

2

In [20]:
#enter solution


2.8 Create a dictionary with the keys "Person1", "Person2", "Person3", "Person4" and the values, 12 ,13 ,15 ,11
save it as **person_dict**. Create a pandas series out of this dictionary and save it as **person_pd**.

In [21]:
person_dict = {"Person1": 12, "Person2": 13, "Person3": 15, "Person4": 11}
print(person_dict)
person_pd = pd.Series(person_dict)
person_pd

{'Person1': 12, 'Person2': 13, 'Person3': 15, 'Person4': 11}


Person1    12
Person2    13
Person3    15
Person4    11
dtype: int64

In [22]:
#enter solution


2.9 Get the values for Person3

In [23]:
person_pd["Person3"]

15

In [24]:
#enter solution


2.10 Get the values from Person2 to Person4

In [25]:
person_pd["Person2":"Person4"]

Person2    13
Person3    15
Person4    11
dtype: int64

In [26]:
#enter solution


2.11 Get a pandas series from the following dictionary with only index 3 and 2 

In [27]:
test_dict = {2: "a", 3: "c", 1: "a"}

data = pd.Series(test_dict, index= [3,2])
data

3    c
2    a
dtype: object

In [28]:
#enter solution


#### Task 3 Pandas DataFrame Object

3.1 Create two dictionaries named person_number_dict and person_wage dict with the keys "Person1", "Person2", "Person3", "Person4". 
The values for person_number_dict: 123 , 124 , 125 , 126
The values for person_wage_dict: 10000, 12000 , 9000, 5000

In [29]:
person_number_dict = {"Person1": 123, "Person2": 124, "Person3": 125, "Person4": 126}
person_wage_dict = {"Person1": 10000, "Person2": 12000, "Person3": 9000, "Person4": 5000}

In [30]:
#enter solution


3.2 Create two pandas series with the dictionaries before. Named person_number_pd and person_wage_pd.

In [31]:
person_number_pd = pd.Series(person_number_dict)
person_wage_pd = pd.Series(person_wage_dict)

In [32]:
#enter solution


3.3 Create a data frame with the index set as "Person1", "Person2" ... etc. and the column named as "per. number" and "wage". Fill in the pandas series from before. Save it in the variable **data**

In [33]:
data = pd.DataFrame({"per. number": person_number_pd, "wage": person_wage_pd})
print(data)

         per. number   wage
Person1          123  10000
Person2          124  12000
Person3          125   9000
Person4          126   5000


In [34]:
#enter solution


3.4 Get the indices from the **data** set

In [35]:
data.index

Index(['Person1', 'Person2', 'Person3', 'Person4'], dtype='object')

In [36]:
#enter solution


3.5 Get the column names from the **data** set

In [37]:
data.columns

Index(['per. number', 'wage'], dtype='object')

In [38]:
#enter solution


3.6 Get the column for "wage" from the **data** set

In [39]:
data["wage"]

Person1    10000
Person2    12000
Person3     9000
Person4     5000
Name: wage, dtype: int64

In [40]:
#enter solution


#### Task 4 Create Panda DataFrames

4.1 Create a Panda DataFrame from **person_wage_pd**

In [41]:
data = pd.DataFrame(person_wage_pd, columns= ["wage"])
data

wage
Person1  10000
Person2  12000
Person3   9000
Person4   5000

In [42]:
#enter solution


4.2 Create a Panda DataFrame from the given dictionary

In [43]:
x_dict = [{"a":i ,"b":i*2 , "c": i**3} for i in range(3)]

pd.DataFrame(x_dict)

a  b  c
0  0  0  0
1  1  2  1
2  2  4  8

In [44]:
x_dict = [{"a":i ,"b":i*2 , "c": i**3} for i in range(3)]

#enter solution


4.3 Create a Panda DataFrame from the two following dictionaries

In [45]:
x_dict = {"a": 1, "b": 2}
y_dict = {"b": 4, "c": 3}

x_pd = pd.DataFrame([x_dict, y_dict])
x_pd

a  b    c
0  1.0  2  NaN
1  NaN  4  3.0

In [46]:
x_dict = {"a": 1, "b": 2}
y_dict = {"b": 4, "c": 3}

#enter solution


4.4 Create a Panda DataFrame from the following Numpy array and lists

In [47]:
np.random.seed(42)
np_data = np.random.rand(3,2)
cols = ["foo", "bar"]
ind = ["a", "b", "c"]

pd.DataFrame(np_data, columns=cols, index= ind)

foo       bar
a  0.374540  0.950714
b  0.731994  0.598658
c  0.156019  0.155995

In [48]:
np.random.seed(42)
np_data = np.random.rand(3,2)
cols = ["foo", "bar"]
ind = ["a", "b", "c"]

#enter solution


4.5 Get the intersection of the follwing two indices

In [49]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [50]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

#enter solution


4.6 Get the union of **indA** and **indB**

In [51]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [52]:
#enter solution


4.7 Get the symmetric difference of **indA** and **indB**

In [53]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [54]:
#enter solution


#### Task 5 Data Indexing and Selection 

5.1 Add 1.25 as index "e" to the Series below

In [55]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index= ["a", "b", "c", "d"])
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [56]:
#enter solution


5.2 Get all data between 0.3 and 0.8 from **data**

In [57]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [58]:
#enter solution


5.3 Get the explicit index 1 from the following data set

In [59]:
data = pd.DataFrame(["a", "b", "c", "d", "e"], index= [1,2,3,4,5],columns= ["First"])
print(data)
data.loc[1]

  First
1     a
2     b
3     c
4     d
5     e


First    a
Name: 1, dtype: object

In [60]:
data = pd.DataFrame(["a", "b", "c", "d", "e"], index= [1,2,3,4,5],columns= ["First"])

#enter solution


5.4 Get the implicit index 1 from **data**

In [61]:
data.iloc[1]

First    b
Name: 2, dtype: object

In [62]:
#enter solution


5.5 Add a column "Yearly wage" with the wages x12 for the following dataset.

In [63]:
person_wage_dict = {"Person1": 10000, "Person2": 12000, "Person3": 7000, "Person4":5000}
person_number_dict = {"Person1": 123, "Person2": 124, "Person3": 125, "Person4": 126}
person_wage_pd = pd.Series(person_wage_dict)
person_number_pd = pd.Series(person_number_dict)
data = pd.DataFrame({"Person Number": person_number_pd,"Person wage": person_wage_pd})
print(data)

data["Yearly wage"] = data["Person wage"] * 12
data


         Person Number  Person wage
Person1            123        10000
Person2            124        12000
Person3            125         7000
Person4            126         5000


Person Number  Person wage  Yearly wage
Person1            123        10000       120000
Person2            124        12000       144000
Person3            125         7000        84000
Person4            126         5000        60000

In [64]:
person_wage_dict = {"Person1": 10000, "Person2": 12000, "Person3": 7000, "Person4":5000}
person_number_dict = {"Person1": 123, "Person2": 124, "Person3": 125, "Person4": 126}
person_wage_pd = pd.Series(person_wage_dict)
person_number_pd = pd.Series(person_number_dict)
data = pd.DataFrame({"Person Number": person_number_pd,"Person wage": person_wage_pd})

#enter solution


5.6 Get the values from **data** as a NumPy array

In [65]:
data.values

array([[  123, 10000],
       [  124, 12000],
       [  125,  7000],
       [  126,  5000]], dtype=int64)

In [66]:
#enter solution


5.7 Transpose **data**

In [67]:
data.T

Person1  Person2  Person3  Person4
Person Number      123      124      125      126
Person wage      10000    12000     7000     5000

In [68]:
#enter solution


5.8 Get the second row from **data** as a NumPy array

In [69]:
data.values[1]

array([  124, 12000], dtype=int64)

In [70]:
#enter solution


5.9 Get the column for ***Person wage*** from **data**

In [71]:
data["Person wage"]

Person1    10000
Person2    12000
Person3     7000
Person4     5000
Name: Person wage, dtype: int64

In [72]:
#enter solution


5.10 Get the implicit indices for the first three rows and first two columns from **data**

In [73]:
data.iloc[:3, :2]

Person Number  Person wage
Person1            123        10000
Person2            124        12000
Person3            125         7000

In [74]:
#enter solution


5.11 Get the data for Person1 to Person3 and the columns Person number and Person wage from **data**

In [75]:
data.loc[:"Person3", : "Person wage"]

Person Number  Person wage
Person1            123        10000
Person2            124        12000
Person3            125         7000

In [76]:
#enter solution


#### Task 6 Operations in Pandas

6.1 Add the following Series together and fill the missing values in A or B with 0

In [79]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])

A.add(B, fill_value= 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [80]:
#enter solution


6.2 Add the following Series together and replace missing values in **A** with the mean of **A.stack()**

In [102]:
A = pd.DataFrame(np.random.randint(0,20, (2,2)),columns=list("AB"))
B = pd.DataFrame(np.random.randint(0,10, (3,3)),columns=list("BAC"))
print(A)
print(B)
fill = A.stack().mean()
print(A.add(B, fill_value=fill))

    A   B
0  14   8
1  19  16
   B  A  C
0  0  9  3
1  6  1  2
2  0  4  0
       A      B      C
0  23.00   8.00  17.25
1  20.00  22.00  16.25
2  18.25  14.25  14.25


In [ ]:
#enter solution


6.3 Substract **B** from **A** (use Pandas operator and Pandas method)

In [107]:
A - B
A.sub(B)

A     B   C
0   5.0   8.0 NaN
1  18.0  10.0 NaN
2   NaN   NaN NaN

In [108]:
#enter solution


6.4 Multiply **A** with **B** (use Pandas operator and Pandas method)

In [109]:
A * B
A.mul(B)

A     B   C
0  126.0   0.0 NaN
1   19.0  96.0 NaN
2    NaN   NaN NaN

In [110]:
#enter solution


6.5 Divide **A** by **B** (use Pandas operator and Pandas method)

In [116]:
A / B
A.div(B)

A         B   C
0   1.555556       inf NaN
1  19.000000  2.666667 NaN
2        NaN       NaN NaN

In [117]:
#enter solution


6.6 Get the modulus of **A** divided by **B** (use Pandas operator and Pandas method)

In [119]:
A % B
A.mod(B)

A    B   C
0  5.0  NaN NaN
1  0.0  4.0 NaN
2  NaN  NaN NaN

In [120]:
#enter solution


6.7 Get **A** to the power of **B** (use Pandas operator and Pandas method)

In [123]:
A ** B
A.pow(B)

A           B    C
0  2.066105e+10         1.0  NaN
1  1.900000e+01  16777216.0  NaN
2           NaN         1.0  1.0

In [124]:
#enter solution


#### Task 7 Handling missing data

7.1 Get the sum of the following array

In [128]:
data = np.array([1, np.nan, 3, 4])

np.nansum(data)

8.0

In [129]:
data = np.array([1, np.nan, 3, 4])

#enter solution


7.2 Get the minimum from **data**

In [130]:
np.nanmin(data)

1.0

In [131]:
#enter solution


7.3 Get the maximum from **data**

In [132]:
np.nanmax(data)

4.0

In [133]:
#enter solution
